# Generated by Django 5.1.5 on 2025-01-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='public_key',
        ),
    ]
