# Generated by Django 5.1.5 on 2025-01-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_reset_token_customuser_reset_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='totp_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
