# Generated by Django 5.1.5 on 2025-01-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_totp_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='totp_key',
        ),
        migrations.AddField(
            model_name='customuser',
            name='encrypted_totp_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
